#
# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█
#


exec-once = libinput-gestures-setup start & 
exec-once = xrdb -merge ~/.Xresources &

exec = hyprshade auto &
# exec = hypridle &
exec-once = kdeconnectd &
# exec-once = sleep 5 && /opt/safing/portmaster/portmaster-start notifier & 
